image: docker:20.10.17

services: 
  - docker:20.10.17-dind

stages:
  - build
  - deploy

Build App Dev:
  stage: build
  script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_TOKEN" $CI_REGISTRY
    - docker build --pull -t registry.gitlab.com/god15/special-needs/backend/api:$CI_COMMIT_SHA -f Dockerfile .
    - docker push registry.gitlab.com/god15/special-needs/backend/api:$CI_COMMIT_SHA
  tags:
    - ssh_runner
  only:
    - develop

Build App Prod:
  stage: build
  script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_TOKEN" $CI_REGISTRY
    - docker build --pull -t registry.gitlab.com/god15/special-needs/backend/api:$CI_COMMIT_TAG -f Dockerfile .
    - docker push registry.gitlab.com/god15/special-needs/backend/api:$CI_COMMIT_TAG
  tags:
    - ssh_runner
  only:
    - tags 

Deploy App Dev:
  stage: deploy
  variables:
    DOCKER_HOST: "$DOCKER_STAGE" 
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
  before_script:
    - mkdir -pv $DOCKER_CERT_PATH
    - echo "$CA_ST" > $DOCKER_CERT_PATH/ca.pem
    - echo "$CA_ST_CERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$CA_ST_KEY" > $DOCKER_CERT_PATH/key.pem
  script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_TOKEN" $CI_REGISTRY
    - docker stop api-nginx-1 api-web-1 api-db-1 || true
    - docker system prune -f --all
    - docker compose -f api.dev.yml up -d
    - rm -rfv $DOCKER_CERT_PATH
  environment:
    name: develop
    url:  "$DOCKER_URL_STAGE"
  needs:
    - Build App Dev
  only:
    - develop
  tags:
    - ssh_runner

#Deploy App Prod:
#  stage: deploy
#  variables:
#    DOCKER_HOST: "$DOCKER_STAGE" 
#    DOCKER_TLS_VERIFY: 1
#    DOCKER_CERT_PATH: "/certs"
#  before_script:
#    - mkdir -pv $DOCKER_CERT_PATH
#    - echo "$CA_ST" > $DOCKER_CERT_PATH/ca.pem
#    - echo "$CA_ST_CERT" > $DOCKER_CERT_PATH/cert.pem
#    - echo "$CA_ST_KEY" > $DOCKER_CERT_PATH/key.pem
#  script:
#    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_TOKEN" $CI_REGISTRY
#    - docker stop api_nginx_1 api_web_1 api_db_1 || true
#    - docker system prune -f --all
#    - docker-compose -f api.yml up -d
#    - rm -rfv $DOCKER_CERT_PATH
#  environment:
#    name: develop
#    url:  "$DOCKER_URL_STAGE"
#  needs:
#    - Build App Prod
#  only:
#    - tags
#  tags:
#    - docker

