# Generated by Django 3.2.16 on 2022-12-09 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(help_text='Выберете логотип', upload_to='company_logo/%Y/%m/%d/', verbose_name='Логотип')),
                ('name', models.CharField(help_text='Укажите наименование компании', max_length=200, verbose_name='Наименование')),
                ('description', models.CharField(help_text='Опишите, чем помогла компания', max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('description', models.TextField(help_text='Напишите отзыв', verbose_name='Отзыв')),
                ('name', models.CharField(help_text='Введите своё Имя и Фамилию', max_length=200, verbose_name='Автор')),
                ('images', models.ImageField(blank=True, help_text='Ваша фотография', upload_to='feedback_photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Введите дату создания', verbose_name='Дата создания')),
                ('name', models.CharField(help_text='Введите заголовок новости', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Введите текст новости', verbose_name='Содержание')),
                ('video', models.URLField(blank=True, help_text='Вставьте ссылку на видео', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости студии',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(help_text='Выберите фотографию человека', upload_to='people_photo/%Y/%m/%d/', verbose_name='Фотография')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=200, verbose_name='Фамилия')),
                ('description', models.CharField(help_text='Напишите роль в проекте', max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Playbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование мероприятия', max_length=200, verbose_name='Наименование')),
                ('address', models.CharField(help_text='Введите адрес мероприятия', max_length=200, verbose_name='Адрес')),
                ('date', models.DateTimeField(help_text='Введите время проведения', verbose_name='Время проведения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену за билет', max_digits=19, verbose_name='Цена билета')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиши',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите заголовок мероприятия', max_length=200, verbose_name='Заголовок')),
                ('address', models.CharField(help_text='Введите адрес проведения', max_length=200, verbose_name='Адрес')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Введите запланированную дату', verbose_name='Запланировано')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', upload_to='news_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.news')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
