# Generated by Django 3.2.16 on 2022-12-28 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Введите своё Имя и Фамилию', max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Введите не менее 2 символов')], verbose_name='Автор'),
        ),
    ]
