# Generated by Django 3.2.16 on 2022-12-30 14:56

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(help_text='Напишите отзыв', max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Введите не менее 10 символов')], verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Введите своё Имя и Фамилию', max_length=200, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['UNICODE'], message='Введите корректное значение', regex="^[a-zа-яё ,.'-]+$"), django.core.validators.MinLengthValidator(limit_value=2, message='Введите не менее 2 символов')], verbose_name='Автор'),
        ),
    ]
