# Generated by Django 3.2.16 on 2023-01-14 14:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221230_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Введите своё Имя и Фамилию', max_length=200, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Введите корректное значение', regex="^[a-zа-яё ,.'-]+$"), django.core.validators.MinLengthValidator(limit_value=2, message='Введите не менее 2 символов')], verbose_name='Автор'),
        ),
    ]
